with-expecter: true
all: true
dir: "{{.InterfaceDir}}/mocks"
filename: "{{.InterfaceName}}.go"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
packages:
  github.com/azisuazusa/todo-cli:
    config:
      recursive: true
