// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/azisuazusa/todo-cli/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// IntegrationRepository is an autogenerated mock type for the IntegrationRepository type
type IntegrationRepository struct {
	mock.Mock
}

type IntegrationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *IntegrationRepository) EXPECT() *IntegrationRepository_Expecter {
	return &IntegrationRepository_Expecter{mock: &_m.Mock}
}

// GetTasks provides a mock function with given fields: ctx, projectID, details
func (_m *IntegrationRepository) GetTasks(ctx context.Context, projectID string, details map[string]string) (entity.Tasks, error) {
	ret := _m.Called(ctx, projectID, details)

	if len(ret) == 0 {
		panic("no return value specified for GetTasks")
	}

	var r0 entity.Tasks
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string) (entity.Tasks, error)); ok {
		return rf(ctx, projectID, details)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string) entity.Tasks); ok {
		r0 = rf(ctx, projectID, details)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entity.Tasks)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]string) error); ok {
		r1 = rf(ctx, projectID, details)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IntegrationRepository_GetTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTasks'
type IntegrationRepository_GetTasks_Call struct {
	*mock.Call
}

// GetTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - details map[string]string
func (_e *IntegrationRepository_Expecter) GetTasks(ctx interface{}, projectID interface{}, details interface{}) *IntegrationRepository_GetTasks_Call {
	return &IntegrationRepository_GetTasks_Call{Call: _e.mock.On("GetTasks", ctx, projectID, details)}
}

func (_c *IntegrationRepository_GetTasks_Call) Run(run func(ctx context.Context, projectID string, details map[string]string)) *IntegrationRepository_GetTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]string))
	})
	return _c
}

func (_c *IntegrationRepository_GetTasks_Call) Return(_a0 entity.Tasks, _a1 error) *IntegrationRepository_GetTasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IntegrationRepository_GetTasks_Call) RunAndReturn(run func(context.Context, string, map[string]string) (entity.Tasks, error)) *IntegrationRepository_GetTasks_Call {
	_c.Call.Return(run)
	return _c
}

// NewIntegrationRepository creates a new instance of IntegrationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIntegrationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IntegrationRepository {
	mock := &IntegrationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
