// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/azisuazusa/todo-cli/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// TaskRepository is an autogenerated mock type for the TaskRepository type
type TaskRepository struct {
	mock.Mock
}

type TaskRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskRepository) EXPECT() *TaskRepository_Expecter {
	return &TaskRepository_Expecter{mock: &_m.Mock}
}

// Upsert provides a mock function with given fields: ctx, task
func (_m *TaskRepository) Upsert(ctx context.Context, task entity.Task) error {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Task) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TaskRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type TaskRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - task entity.Task
func (_e *TaskRepository_Expecter) Upsert(ctx interface{}, task interface{}) *TaskRepository_Upsert_Call {
	return &TaskRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, task)}
}

func (_c *TaskRepository_Upsert_Call) Run(run func(ctx context.Context, task entity.Task)) *TaskRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Task))
	})
	return _c
}

func (_c *TaskRepository_Upsert_Call) Return(_a0 error) *TaskRepository_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TaskRepository_Upsert_Call) RunAndReturn(run func(context.Context, entity.Task) error) *TaskRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewTaskRepository creates a new instance of TaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskRepository {
	mock := &TaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
