// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/azisuazusa/todo-cli/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// ProjectRepository is an autogenerated mock type for the ProjectRepository type
type ProjectRepository struct {
	mock.Mock
}

type ProjectRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ProjectRepository) EXPECT() *ProjectRepository_Expecter {
	return &ProjectRepository_Expecter{mock: &_m.Mock}
}

// GetSelectedProject provides a mock function with given fields: ctx
func (_m *ProjectRepository) GetSelectedProject(ctx context.Context) (entity.Project, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSelectedProject")
	}

	var r0 entity.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (entity.Project, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) entity.Project); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(entity.Project)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProjectRepository_GetSelectedProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSelectedProject'
type ProjectRepository_GetSelectedProject_Call struct {
	*mock.Call
}

// GetSelectedProject is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ProjectRepository_Expecter) GetSelectedProject(ctx interface{}) *ProjectRepository_GetSelectedProject_Call {
	return &ProjectRepository_GetSelectedProject_Call{Call: _e.mock.On("GetSelectedProject", ctx)}
}

func (_c *ProjectRepository_GetSelectedProject_Call) Run(run func(ctx context.Context)) *ProjectRepository_GetSelectedProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ProjectRepository_GetSelectedProject_Call) Return(_a0 entity.Project, _a1 error) *ProjectRepository_GetSelectedProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProjectRepository_GetSelectedProject_Call) RunAndReturn(run func(context.Context) (entity.Project, error)) *ProjectRepository_GetSelectedProject_Call {
	_c.Call.Return(run)
	return _c
}

// NewProjectRepository creates a new instance of ProjectRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProjectRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProjectRepository {
	mock := &ProjectRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
