// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// SettingRepository is an autogenerated mock type for the SettingRepository type
type SettingRepository struct {
	mock.Mock
}

type SettingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SettingRepository) EXPECT() *SettingRepository_Expecter {
	return &SettingRepository_Expecter{mock: &_m.Mock}
}

// Sync provides a mock function with given fields: ctx
func (_m *SettingRepository) Sync(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Sync")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SettingRepository_Sync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sync'
type SettingRepository_Sync_Call struct {
	*mock.Call
}

// Sync is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SettingRepository_Expecter) Sync(ctx interface{}) *SettingRepository_Sync_Call {
	return &SettingRepository_Sync_Call{Call: _e.mock.On("Sync", ctx)}
}

func (_c *SettingRepository_Sync_Call) Run(run func(ctx context.Context)) *SettingRepository_Sync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *SettingRepository_Sync_Call) Return(_a0 error) *SettingRepository_Sync_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SettingRepository_Sync_Call) RunAndReturn(run func(context.Context) error) *SettingRepository_Sync_Call {
	_c.Call.Return(run)
	return _c
}

// NewSettingRepository creates a new instance of SettingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSettingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SettingRepository {
	mock := &SettingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
