// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/azisuazusa/todo-cli/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

type UseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *UseCase) EXPECT() *UseCase_Expecter {
	return &UseCase_Expecter{mock: &_m.Mock}
}

// AddWorklog provides a mock function with given fields: ctx, task, timeSpent
func (_m *UseCase) AddWorklog(ctx context.Context, task entity.Task, timeSpent time.Duration) error {
	ret := _m.Called(ctx, task, timeSpent)

	if len(ret) == 0 {
		panic("no return value specified for AddWorklog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Task, time.Duration) error); ok {
		r0 = rf(ctx, task, timeSpent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UseCase_AddWorklog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddWorklog'
type UseCase_AddWorklog_Call struct {
	*mock.Call
}

// AddWorklog is a helper method to define mock.On call
//   - ctx context.Context
//   - task entity.Task
//   - timeSpent time.Duration
func (_e *UseCase_Expecter) AddWorklog(ctx interface{}, task interface{}, timeSpent interface{}) *UseCase_AddWorklog_Call {
	return &UseCase_AddWorklog_Call{Call: _e.mock.On("AddWorklog", ctx, task, timeSpent)}
}

func (_c *UseCase_AddWorklog_Call) Run(run func(ctx context.Context, task entity.Task, timeSpent time.Duration)) *UseCase_AddWorklog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Task), args[2].(time.Duration))
	})
	return _c
}

func (_c *UseCase_AddWorklog_Call) Return(_a0 error) *UseCase_AddWorklog_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UseCase_AddWorklog_Call) RunAndReturn(run func(context.Context, entity.Task, time.Duration) error) *UseCase_AddWorklog_Call {
	_c.Call.Return(run)
	return _c
}

// NewUseCase creates a new instance of UseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UseCase {
	mock := &UseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
